create-pages:
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  pages: true # specifies that this is a Pages job and publishes the default public directory
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
