pages:
  stage: deploy
  image: alpine:latest 
  
  script:
    - echo "Origami Linux Website Updating....."
  
  artifacts:
    paths:
      - /
      
  rules:
    # Only run this job on your default branch
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'